### ISSUE TITLE
Access the user’s route data for a workout

### ISSUE THREAD

**Issue by nguyening20** [agencyenterprise/react-native-health#208] opened 2022-02-14 23:51 UTC
**Is your feature request related to a problem? Please describe.**
I'd like to access the user's route data from a workout.

**Describe the solution you'd like**
Possibly add a new method called "getWorkoutRoute"

**Additional context**
Hey guys, I think this feature would be useful to have. The data could be used for displaying cool visuals and for data analytics.

This [article](https://developer.apple.com/documentation/healthkit/workouts_and_activity_rings/reading_route_data?language=objc) is a good reference.

Although I'm not familiar with Obj-C, I attempted to implement this into my project.

What I have so far:
- New Permission added "WorkoutRoute"
- Exported a method getWorkoutRoute (id is required in the input. Id can be found from a workout. [[sample UUID] UUIDString])
- Added a method to Methods_Workout called "workout_getRoutes" that calls "fetchWorkoutSample" followed by "fetchWorkoutRoute"
- Added a method to Queries called "fetchWorkoutSample" that retrieves HKWorkout  for the UUID provided
- Added a method to Queries called "fetchWorkoutRoute"  that uses the HKWorkout from the "fetchWorkoutSample" method to retrieve the workout route data. This method executes two queries in reference to this [article](https://developer.apple.com/documentation/healthkit/workouts_and_activity_rings/reading_route_data?language=objc).

Edit: After struggling for over a day, I was able to successfully get all the location data for a route :)

Issues/Questions:
- I'm not sure if a workout can have multiple routes associated with it. I assumed one. If a workout can have multiple routes, I'm not sure how to perform an async batch query for each route to fetch the location data and then send that data through the callback function.

I will add the configuration to my fork.

**Comment by mgfuller333** [comment] 2022-03-19 20:33
Hey How did you pull the UUID string from the anchored workout? I am not sure how to access that array of data

**Comment by nguyening20** [comment] 2022-03-19 22:38
In the [getAnchoredWorkouts](https://github.com/agencyenterprise/react-native-health/blob/master/docs/getAnchoredWorkouts.md) query, you can access the UUID string from the Id field. It's not in the documentation, but you should see it in an anchored workout response. I hope this helps.

**Comment by mgfuller333** [comment] 2022-03-24 19:16
Ok if you're able to hop in discord sometime and brainstorm with me how to do it, I have swift code made I just need help integrating it into react native.

**Comment by nguyening20** [comment] 2022-03-25 01:12
Yeah, I can most definitely try to help you out.

**Comment by devth** [comment] 2022-04-11 19:10
Any updates on this? I'd love to be able to access this data.

**Comment by nguyening20** [comment] 2022-04-15 18:23
@devth I'm considering opening a PR in the near future, but feel free to take a look at [my fork](https://github.com/nguyening20/react-native-health).

**Comment by devth** [comment] 2022-04-15 18:33
Thanks @nguyening20, I'll check out your fork! And please do open a PR if you can.

**Comment by walterholohan** [comment] 2022-06-14 12:21
@nguyening20 amazing stuff, I need to use workoutRoute too, will use your fork for now but would be great if you could raise a PR.

@macelai are you still maintaining this repo?

**Comment by mgfuller333** [comment] 2022-06-14 13:07
![image](https://user-images.githubusercontent.com/66493966/173584358-506ca88c-c05c-460d-9297-478e20678dda.png)

**Comment by mgfuller333** [comment] 2022-06-14 13:08
> issue

Just request HKWorkoutRoutes and you should get it.

**Comment by macelai** [comment] 2022-06-14 13:12
hey @walterholohan, we are open to new PRs

**Comment by nguyening20** [comment] 2022-06-14 13:21
@walterholohan This method only allows you to retrieve the workout route. It looks like you are trying to ask for write permissions. Moving AppleHealthKit.Constants.Permissions.WorkoutRoute to the read array should solve the issue here.

**Comment by walterholohan** [comment] 2022-06-14 13:27
@macelai I have raised a PR https://github.com/agencyenterprise/react-native-health/pull/222/files that will allow users to ask for write permissions for WorkoutRoute

**Comment by walterholohan** [comment] 2022-06-14 13:34
@nguyening20 apologies but it seems that since I forked off your repo and then tried to create a PR against this repo it has included all your changes in the PR too. Can you take a review of the changes - https://github.com/agencyenterprise/react-native-health/pull/222

**Comment by nguyening20** [comment] 2022-06-14 13:44
@walterholohan I don't see a method to handle saving any workout route data to Apple HealthKit so I don't necessarily understand why you would need to ask for write permissions in this case.

**Comment by walterholohan** [comment] 2022-06-14 14:26
@nguyening20 we have built an apple watch app for our RN app (https://www.runna.com/) that tracks a user while running. And as part of this, we write to the workoutRoute in HealthKit. This was the only library I could find that would allow us to ask the user to accept write permissions for health kit via the mobile app.

**Comment by nguyening20** [comment] 2022-06-14 15:59
@walterholohan Please consider sharing or adding how you configured writing/saving workout routes to Apple HealthKit. I know @mgfuller333 and I would like this functionality included with this library. Thanks.

**Comment by walterholohan** [comment] 2022-06-14 16:16
@nguyening20 will do. At the moment we are saving routes to HealthKit via the apple watch app, once we have this fully working I can share the swift code with you.

**Comment by walterholohan** [comment] 2022-06-14 16:17
@nguyening20 I will close my PR as its just a duplicate of yours

**Closed** 2022-08-04 14:12 UTC
Labels: enhancement
